// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vekgzsycpfjoezxshhrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZla2d6c3ljcGZqb2V6eHNoaHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzgwMDcsImV4cCI6MjA2Mzg1NDAwN30.MMmN42ftTQoOJryd_u0s5ZrUzK5ODnm6DOA2ArXUI08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);